apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse_main
    url: http://clickhouse:8123
    isDefault: true
    jsonData:
      server: clickhouse
      port: 8123
      username: default
      defaultDatabase: space_pulse
